# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5c1cb44d-7d83-49db-9026-60d0919bafaf";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E7F7-40C6";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/ssd-big" = {
    device = "/dev/disk/by-uuid/2dbc264f-9213-4946-9444-dd830ab4fcde";
    fsType = "btrfs";
  };

  fileSystems."/mnt/m2" = {
    device = "/dev/disk/by-uuid/694119c6-4b91-414d-94aa-282a2fb15254";
    fsType = "btrfs";
  };

  fileSystems."/mnt/mega-m2" = {
    device = "/dev/disk/by-uuid/bff0db9f-0b97-4d3c-8f6b-8cbb4ff2ae0e";
    fsType = "btrfs";
  };

  fileSystems."/mnt/vault" = {
    device = "/dev/disk/by-uuid/9b1fa832-7114-4ed0-a7eb-59bc44c70b03";
    fsType = "btrfs";
  };

  fileSystems."/mnt/ssd-huge" = {
    device = "/dev/disk/by-uuid/d5dfee8d-2b43-4282-8544-5a5f3314cd95";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/45d131f4-40bd-49e2-bb44-c89929c8238b"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

